=== RhysJonesTM/schemas/src/schemas/pdtf-transaction.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/Property-Data-Trust-Framework/schemas/master/src/schemas/pdtf-transaction.json",
  "type": "object",
  "title": "Property Data Trust Framework Transaction Schema",
  "description": "A schema defining the PDTF transaction data structure, supporting mapping to BASPI, Law Society and RICS Data Schema elements.",
  "required": [
    "$schema",
    "transactionId",
    "status",
    "participants",
    "propertyPack"
  ],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "transactionId": {
      "title": "UUID for the transaction",
      "type": "string",
      "format": "uuid"
    },
    "status": {
      "type": "string",
      "enum": ["active", "cancelled", "completed"]
    },
    "participants": {
      "title": "Transaction participants",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "title": "Participant Details",
        "required": ["name", "email", "role"],
        "properties": {
          "name": {
            "title": "Name",
            "type": "object",
            "required": ["firstName", "lastName"],
            "properties": {
              "firstName": {
                "title": "First name",
                "type": "string"
              },
              "middleName": {
                "title": "Middle name(s)",
                "type": "string"
              },
              "lastName": {
                "title": "lastName",
                "type": "string"
              },
              "preferredName": {
                "title": "Preferred name / known as",
                "type": "string"
              }
            }
          },
          "dateOfBirth": {
            "title": "Date of birth",
            "type": "string",
            "format": "date"
          },
          "phone": {
            "title": "Phone number",
            "type": "string"
          },
          "email": {
            "title": "Email address",
            "type": "string",
            "format": "email"
          },
          "address": {
            "title": "Address",
            "$ref": "#/$defs/address"
          },
          "organisation": {
            "title": "Organisation",
            "type": "string"
          },
          "organisationReference": {
            "title": "Reference",
            "type": "string"
          },
          "role": {
            "title": "Role",
            "type": "string",
            "enum": [
              "Seller",
              "Seller's Conveyancer",
              "Prospective Buyer",
              "Buyer",
              "Buyer's Conveyancer",
              "Estate Agent"
            ]
          }
        }
      }
    },
    "propertyPack": {
      "title": "Property Pack",
      "type": "object",
      "properties": {
        "materialFacts": {
          "$ref": "https://raw.githubusercontent.com/Property-Data-Trust-Framework/schemas/master/src/schemas/baspi-a-material-facts.json"
        },
        "additionalLegalInfo": {
          "$ref": "https://raw.githubusercontent.com/Property-Data-Trust-Framework/schemas/master/src/schemas/baspi-b-legal-information.json"
        },
        "titlesToBeSold": {
          "RDSRef": "",
          "title": "Title(s) as registered with HMLR which are included in the sale",
          "type": "array",
          "items": {
            "type": "object",
            "title": "Registered Title",
            "properties": {
              "titleNumber": {
                "RDSRef": "",
                "title": "Title Number",
                "type": "string"
              },
              "tenure": {
                "RDSRef": "",
                "title": "Tenure",
                "description":  "Tenure (property ownership) of the title",
                "type": "string",
                "enum": [
                  "Freehold",
                  "Leasehold",
                  "Commonhold",
                  "Flying Freehold",
                  "Unknown",
                  "Other"
                ]
              },
              "titleExtents": {
                "RDSRef": "",
                "title": "Title Extents",
                "description": "One or more index polygons describing indicative location of registered title from National Polygon Dataset",
                "type": "array",
                "items": {
                  "$ref": "https://geojson.org/schema/GeoJSON.json"
                }
              },
              "registerExtract": {
                "title": "HMLR Register Extract",
                "$ref": "https://raw.githubusercontent.com/Property-Data-Trust-Framework/schemas/master/src/schemas/title-deed.json"
              }
            }
          }
        },
        "energyPerformanceCertificate": {
          "RDSRef": "",
          "title": "Energy Performance Certificate",
          "$ref": "https://raw.githubusercontent.com/Property-Data-Trust-Framework/schemas/master/src/schemas/energy-performance-certificate.json"
        },
        "risks": {
          "RDSRef": "",
          "title": "Risks",
          "type": "object",
          "properties": {
            "coalMining": {
              "title": "Coal mining",
              "$ref": "#/$defs/riskIndicatorAndSearch"
            },
            "flood": {
              "title": "Flood",
              "$ref": "#/$defs/riskIndicatorAndSearch"
            },
            "miningAndGroundStability": {
              "title": "Mining and ground stability",
              "type": "object",
              "properties": {
                "bathStone": {
                  "title": "Bath Stone",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "metalliferousTin": {
                  "title": "Matalliferous (Tin)",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "kaolinAndBallClay": {
                  "title": "Kaolin and ball clay",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "limestone": {
                  "title": "Limestone",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "brine": {
                  "title": "Brine",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "groundStability": {
                  "title": "Ground stability",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "nonCoalMining": {
                  "title": "Non coal mining",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "groundMovement": {
                  "title": "Ground movement",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "mineral": {
                  "title": "Mineral",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                }
              }
            },
            "energyAndInfrastructure": {
              "title": "Energy and infrastructure",
              "type": "object",
              "properties": {
                "hs2": {
                  "title": "HS2",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "crossrail": {
                  "title": "Crossrail",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "londonUnderground": {
                  "title": "London Underground",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "energyExploration": {
                  "title": "Energy exploration",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "windFarms": {
                  "title": "Wind farms",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "solarFarms": {
                  "title": "Solar farms",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                },
                "renewablePowerPlants": {
                  "title": "Renewable power plants",
                  "$ref": "#/$defs/riskIndicatorAndSearch"
                }
              }
            }
          }
        }
      }
    }
  },
  "$defs": {
    "address": {
      "type": "object",
      "properties": {
        "line1": {
          "title": "Address 1",
          "type": "string",
          "minLength": 1
        },
        "line2": {
          "title": "Address 2",
          "type": "string"
        },
        "town": {
          "title": "Town",
          "type": "string"
        },
        "county": {
          "title": "County",
          "type": "string"
        },
        "postcode": {
          "title": "Postcode",
          "type": "string",
          "minLength": 1
        }
      },
      "required": ["line1", "postcode"]
    },
    "riskIndicatorAndSearch": {
      "type": "object",
      "properties": {
        "hasRisk": {
          "title": "",
          "type": "string",
          "enum": ["Yes", "No"]
        }
      },
      "required": ["hasRisk"]
    }
  }
}

=== RhysJonesTM/schemas/src/examples/exampleTransaction.json
{
  "$schema": "https://raw.githubusercontent.com/Property-Data-Trust-Framework/schemas/master/src/schemas/pdtf-transaction.json",
  "transactionId": "3e4666bf-d5e5-4aa7-b8ce-cefe41c7568a",
  "status": "active",
  "participants": [
    {
      "name": {
        "firstName": "Peter",
        "lastName": "Hetherington-Smythe"
      },
      "dateOfBirth": "1975-12-25",
      "phone": "07777 222333",
      "email": "peter@theseller.com",
      "address": { "line1": "47 Park Road", "postcode": "AL3 5AF" },
      "role": "Seller"
    }
  ],
  "propertyPack": {
    "materialFacts": {
      "uprn": 1241304304,
      "address": {
        "line1": "47 Park Road",
        "line2": "",
        "town": "HARPENDEN",
        "county": "Herts",
        "postcode": "AL3 5AF"
      },

      "delayFactors": {
        "hasDelayFactors": { "yesNo": "No" }
      },
      "ownership": {
        "ownershipType": "Freehold"
      },
      "parking": {
        "parkingArrangements": {
          "parkingArrangementsType": "Other",
          "otherParkingType": "Garage and double width driveway"
        },
        "electricVehicleChargingPoint": { "yesNo": "No" }
      },
      "listingAndConservation": {
        "isListed": {
          "yesNo": "No"
        },
        "isConservationArea": {
          "yesNo": "No"
        },
        "hasTreePreservationOrder": {
          "yesNo": "No"
        }
      },
      "typeOfConstruction": {
        "isStandardForm": {
          "yesNo": "Yes"
        },
        "hasFlammableExternalWallSystem": "No"
      },
      "energyEfficiency": {
        "energyEfficiencyRating": "A",
        "hasSprayFoamInstalled": {
          "yesNo": "No"
        }
      },
      "councilTax": {
        "councilTaxBand": "A",
        "councilTaxAffectingAlterations": {
          "yesNo": "No"
        }
      },
      "disputesAndComplaints": {
        "hasDisputesAndComplaints": {
          "yesNo": "No"
        }
      },
      "alterationsAndChanges": {
        "hasStructuralAlterations": {
          "buildingRegApproval": {
            "yesNo": "Yes"
          },
          "planningPermission": {
            "yesNo": "Yes"
          },
          "listedBuildingConsent": {
            "yesNo": "Not required",
            "reasons": "Not listed building\n"
          },
          "deedRestrictionConsent": {
            "yesNo": "Not required",
            "reasons": "Retrospective consent obtained from leasehold provider but property now freehold"
          },
          "unfinished": {
            "yesNo": "No"
          },
          "yesNo": "Yes",
          "details": "Bedroom and ensuite shower room extension 2005"
        },
        "windowReplacementsSince2002": {
          "buildingRegApproval": {
            "yesNo": "Not required",
            "reasons": "Not required"
          },
          "planningPermission": {
            "yesNo": "Not required",
            "reasons": "Not required"
          },
          "listedBuildingConsent": {
            "yesNo": "Not required",
            "reasons": "Not listed building"
          },
          "deedRestrictionConsent": {
            "yesNo": "Not required",
            "reasons": "None required"
          },
          "unfinished": {
            "yesNo": "No"
          },
          "yesNo": "Yes",
          "details": "New front door added 2016"
        },
        "hasAddedConservatory": {
          "buildingRegApproval": {
            "yesNo": "Not required",
            "reasons": "Added as part of initial build"
          },
          "planningPermission": {
            "yesNo": "Not required",
            "reasons": "Added as part of initial build"
          },
          "listedBuildingConsent": {
            "yesNo": "Not required",
            "reasons": "Not listed building"
          },
          "deedRestrictionConsent": {
            "yesNo": "Not required",
            "reasons": "Added as part of initial build and deeds"
          },
          "unfinished": {
            "yesNo": "No"
          },
          "yesNo": "Yes",
          "details": "Conservatory added during house build in 1990 and exterior quality door separates the conservatory from the kitchen/dining room"
        },
        "planningPermissionBreaches": {
          "yesNo": "No"
        },
        "unresolvedPlanningIssues": {
          "yesNo": "No"
        }
      },
      "notices": {
        "neighbourDevelopment": {
          "yesNo": "No"
        },
        "planningApplication": {
          "yesNo": "No"
        },
        "requiredMaintenance": {
          "yesNo": "No"
        },
        "listedBuildingApplication": {
          "yesNo": "No"
        },
        "infrastructureProject": {
          "yesNo": "No"
        },
        "partyWallAct": {
          "yesNo": "No"
        },
        "otherNotices": {
          "yesNo": "No"
        }
      },
      "specialistIssues": {
        "dryRotEtcTreatment": {
          "yesNo": "No"
        },
        "containsAsbestos": {
          "yesNo": "No"
        },
        "japaneseKnotweed": {
          "yesNo": "No"
        },
        "subsidenceOrStructuralFault": {
          "yesNo": "No"
        },
        "ongoingHealthOrSafetyIssue": {
          "yesNo": "No"
        }
      },
      "fixturesAndFittings": {
        "itemsToRemove": {
          "yesNo": "No"
        },
        "itemsToInclude": {
          "yesNo": "No"
        }
      },
      "waterAndDrainage": {
        "mainsWater": {
          "maintenanceAgreements": {
            "yesNo": "No"
          },
          "yesNo": "Yes",
          "connected": "Yes",
          "supplier": "Northumbria Water"
        },
        "mainsSurfaceWaterDrainage": {
          "maintenanceAgreements": {
            "yesNo": "No"
          },
          "yesNo": "Yes",
          "connected": "Yes",
          "supplier": "Northumbria Water"
        },
        "mainsFoulDrainage": {
          "maintenanceAgreements": {
            "yesNo": "No"
          },
          "yesNo": "Yes",
          "connected": "Yes",
          "supplier": "Northumbria Water"
        }
      },
      "utilities": {
        "electricity": {
          "maintenanceAgreements": {
            "yesNo": "No"
          },
          "yesNo": "Yes",
          "connected": "Yes",
          "supplier": "Octopus Energy"
        },
        "gas": {
          "maintenanceAgreements": {
            "yesNo": "No"
          },
          "yesNo": "Yes",
          "connected": "Yes",
          "supplier": "Octopus Energy"
        },
        "lpg": {
          "yesNo": "No"
        },
        "oil": {
          "yesNo": "No"
        },
        "telephone": {
          "maintenanceAgreements": {
            "yesNo": "No"
          },
          "yesNo": "Yes",
          "connected": "Yes",
          "supplier": "EE"
        },
        "cableSatelliteTV": {
          "maintenanceAgreements": {
            "yesNo": "No"
          },
          "yesNo": "Yes",
          "connected": "Yes",
          "supplier": "Sky"
        },
        "broadband": {
          "maintenanceAgreements": {
            "yesNo": "No"
          },
          "yesNo": "Yes",
          "connected": "Yes",
          "supplier": "EE"
        },
        "solarPanels": {
          "yesNo": "No"
        },
        "otherServices": {
          "yesNo": "No"
        }
      },
      "greenDealLoan": {
        "hasGreenDealLoan": {
          "yesNo": "No"
        }
      },
      "centralHeating": {
        "hasCentralHeating": "Yes",
        "centralHeatingDetails": {
          "boilerInstallationCertificate": {
            "yesNo": "Yes",
            "details": "Certified installation"
          },
          "heatingInGoodWorkingOrder": {
            "yesNo": "Yes"
          },
          "centralHeatingFuel": "Gas boiler",
          "centralHeatingInstalled": "2016-04-20",
          "heatingLastServiced": "2021-03-26"
        }
      },
      "insurance": {
        "difficultiesObtainingInsurance": {
          "yesNo": "No"
        },
        "insuranceClaims": {
          "yesNo": "No"
        },
        "isInsured": "Yes"
      },
      "boundaries": {
        "partOutsideLegalOwnership": {
          "yesNo": "No"
        },
        "partOnSeparateSiteOrDeed": {
          "yesNo": "No"
        },
        "boundariesDifferFromTitlePlan": {
          "yesNo": "No"
        },
        "boundaryAlterationProposal": {
          "yesNo": "No"
        }
      },
      "rightsAndInformalArrangements": {
        "sharedContributions": {
          "yesNo": "No"
        },
        "neighbouringLandRights": {
          "yesNo": "No"
        },
        "accessRestrictionAttempts": {
          "yesNo": "No"
        },
        "rightsOrArrangements": {
          "publicRightOfWay": {
            "yesNo": "No"
          },
          "rightsofLightOrSupport": {
            "yesNo": "No"
          },
          "rightsCreatedThroughCustom": {
            "yesNo": "No"
          },
          "minesAndMinerals": {
            "yesNo": "No"
          },
          "churchChancel": {
            "yesNo": "No"
          },
          "otherRights": {
            "yesNo": "No"
          }
        }
      },
      "otherIssues": {
        "environmental": {
          "yesNo": "No"
        },
        "excessiveNoise": {
          "yesNo": "No"
        },
        "crime": {
          "yesNo": "No"
        },
        "cautionOrConviction": {
          "yesNo": "No"
        },
        "failedTransactionsInLast12Months": {
          "yesNo": "No"
        },
        "comments": "Not applicable"
      },
      "additionalInformation": {
        "restrictionsOnUseNotCompliedWith": {
          "yesNo": "No"
        },
        "otherMaterialIssue": {
          "yesNo": "No"
        }
      },
      "consumerProtectionRegulationsDeclaration": {
        "consumerProtectionRegulationsResponse": true
      }
    },
    "additionalLegalInfo": {
      "namesOfLegalOwners": [
        {
